@url = http://localhost:3000/jogos

GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "titulo": "DONQUEI CONG",
    "idGenero": 5,
    "idPlataformas":[1]
}

###
PUT {{url}}/4
Content-Type: application/json

{
    "titulo": "Backyardigans - edition one",
    "idGenero": 3,
    "idPlataformas":[1,2,3]
}

###
PATCH {{url}}/5
Content-Type: application/json

{
    "titulo":"Donkey Kong"
}